security:
    enable_authenticator_manager: true
    encoders:
        App\Domain\_mysql\System\Entity\User:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
    providers:
        system_user_email_provider:
            entity:
                class: App\Domain\_mysql\System\Entity\User
        users_in_memory: { memory: null }