version: '3.3'
services:
    bdd:
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        image: mysql
        volumes:
          - db-data:/var/lib/mysql
    nginx:
        image: nginx:alpine
        links:
          - php
        ports:
          - 10101:80
        volumes:
          - .:/var/www
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        environment:
            APP_ENV: prod
        links:
          - bdd
        volumes:
          - .:/var/www
volumes:
    db-data:
        driver: local